# Please provide the github usernames here.
usernames = [
    "brejoc",
    "dincamihai",
    "meaksh",
]

# The repository name with owner: brejoc/my_repo
repos = [
    "saltstack/salt",
    "openSUSE/salt",
    "SUSE/spacewalk",
    "cobbler/cobbler",
    "uyuni-project/uyuni",
]

# The Github API token can either be provided here or via the environment
# variable `GITHUB_API_TOKEN`. This setting has precedence over the
# environment variable.
# github_token = "<insert_github_api_token_here>"